apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: cnr-fundamentals
spec:
  title: Cloud Native Runtimes for VMware Tanzu Fundamentals
  description: A workshop that shows users hands-on how to use the Cloud Native Runtimes for VMware Tanzu
  vendor: eduk8s.io
  authors:
  - Anand Rao 
  - Craig Olrich
  - Evan Anderson
  difficulty: intermediate
  duration: 15m
  url: https://github.com/tanzu-developer-experience/cnr-developer-workshop
  content:
    #image: quay.io/eduk8s/lab-markdown-sample:master
#    image: honnuanand/cnr-dev-fundamentals:0.3
#    image: quay.io/eduk8s/base-environment:master
#    image: olrich/cnr-workshop:0.1
    image: ghcr.io/clue2solve/knative-workshop-eduk8s:latest
    # files: github.com/tanzu-developer-experience/cnr-developer-workshop
    files: github.com/evankanderson/cnr-developer-workshop/files?ref=func-testing
  session:
    env:
    - name: FUNC_REGISTRY
      value: "registry.20.118.148.208.nip.io/func/${session_namespace}"
    namespaces:
      budget: medium
      limits:
        min:
          cpu: 25m
    applications:
      workshop:
        enabled: false
      terminal:
        enabled: true
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      files:
        enabled: true
      docker:
        enabled: true
