#@ load("@ytt:data", "data")

apiVersion: sources.knative.dev/v1beta2 
kind: PingSource 
metadata: 
  name: test-ping-source 
spec: 
  schedule: "*/1 * * * *" 
  data: '{"message": "Hello Eventing!"}' 
  sink: 
   ref: 
    apiVersion: eventing.knative.dev/v1 
    kind: Broker 
    name: default 
    namespace: #@ data.values.sessionns
